### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by roodrallec** [leeeeeeo/yousaidthat-tf#2]
Have you been able to replicate the speech2vid model from the "yousaidthat" paper successfully? Will you try to, or would you like some help, to replicate the second network they suggest in the paper, the one with the context encoder?

<img width="862" alt="Screen Shot 2019-05-08 at 22 43 19" src="https://user-images.githubusercontent.com/8702656/57410449-b71a1c00-71e2-11e9-8106-86ad2f699f9c.png">

**Comment by leeeeeeo** [comment]
The context encoder is proposed in the IJCV version. Sorry I didn't implement that.

**Comment by thekeviv** [comment]
@roodrallec Did you find a pre-trained model for the yousaidthat paper? I want to implement it and need some help approaching the problem, if you haven't found it, would you like collaborating on it to start work on that?

**Comment by roodrallec** [comment]
@thekeviv There's a pretrained matlab model for the paper https://github.com/joonson/yousaidthat
